"""
Django settings for XHVIT project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--9g#3!jqpcf(&fl)wo_j53k)plmh^l%c6$#qw3*nxdo763jc+1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Diagnosis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'XHVIT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'TEMPLATES'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'XHVIT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Your existing static folder
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


XHVIT_MODEL_PATH = BASE_DIR / 'models' 


XHVIT_MODEL_CONFIG = {
    'brain_tumor': {
        'name': 'Brain Tumor Classifier',
        'description': 'Classifies brain MRI into 4 types: Glioma, Meningioma, Pituitary, No Tumor',
        'num_classes': 4,
        'class_names': ['glioma', 'meningioma', 'pituitary', 'notumor'],
        'model_file': 'brain_tumor_best.pth',
        'img_size': 224,
        'icon': 'brain',
        'color': '#e74c3c'
    },
    'fracture': {
        'name': 'Fracture Classifier (FracAtlas)',
        'description': 'Detects bone fractures in X-ray images (FracAtlas dataset)',
        'num_classes': 2,
        'class_names': ['normal', 'fracture'],
        'model_file': 'fracture_best.pth',
        'img_size': 224,
        'icon': 'bone',
        'color': '#f39c12'
    },
    'fracture_multi': {
        'name': 'Fracture Classifier (Multi-Region)',
        'description': 'Detects fractures across multiple body regions in X-rays',
        'num_classes': 2,
        'class_names': ['normal', 'fracture'],
        'model_file': 'fracture_multi_best.pth',
        'img_size': 224,
        'icon': 'bone',
        'color': '#f1c40f'
    },
    'tb_chest': {
        'name': 'TB Chest X-ray Detector',
        'description': 'Detects Tuberculosis from chest X-ray images',
        'num_classes': 2,
        'class_names': ['normal', 'tuberculosis'],
        'model_file': 'tb_chest_best.pth',
        'img_size': 224,
        'icon': 'lungs',
        'color': '#3498db'
    },
    'diabetic_retinopathy': {
        'name': 'Diabetic Retinopathy Classifier',
        'description': 'Classifies diabetic retinopathy severity (0-4) from retina images',
        'num_classes': 5,
        'class_names': ['No_DR', 'Mild', 'Moderate', 'Severe', 'Proliferate_DR'],
        'model_file': 'diabetic_retinopathy_best.pth',
        'img_size': 224,
        'icon': 'eye',
        'color': '#2ecc71'
    },
    'skin_cancer': {
        'name': 'Skin Cancer Classifier',
        'description': 'Classifies skin lesions into 7 categories (HAM10000)',
        'num_classes': 7,
        'class_names': ['akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc'],
        'model_file': 'skin_cancer_best.pth',
        'img_size': 224,
        'icon': 'skin',
        'color': '#9b59b6'
    },
    'pneumonia': {
        'name': 'Pneumonia Detector',
        'description': 'Detects pneumonia from chest X-ray images',
        'num_classes': 2,
        'class_names': ['normal', 'pneumonia'],
        'model_file': 'pneumonia_best.pth',
        'img_size': 224,
        'icon': 'lungs',
        'color': '#e74c3c'
    }
}

# settings.py

# Login URL - where users are redirected when they need to log in
LOGIN_URL = '/login/'  # or 'Diagnosis:login'

# Login redirect URL - where users go after successful login
LOGIN_REDIRECT_URL = '/dashboard/'

# Logout redirect URL - where users go after logout
LOGOUT_REDIRECT_URL = '/'