# Generated by Django 5.2.15 on 2026-07-24 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('brain_tumor', 'Brain Tumor'), ('bone_fracture', 'Bone Fracture'), ('tuberculosis', 'Tuberculosis'), ('diabetic_retinopathy', 'Diabetic Retinopathy'), ('skin_cancer', 'Skin Cancer'), ('pneumonia', 'Pneumonia'), ('fracatlas', 'FracAtlas'), ('custom', 'Custom Model')], max_length=50, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('num_classes', models.IntegerField(default=2)),
                ('class_names', models.JSONField(default=list)),
                ('model_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Info',
                'verbose_name_plural': 'AI Model Infos',
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MRI', 'MRI'), ('CT', 'CT'), ('X-ray', 'X-ray'), ('Micro', 'Micro'), ('auto', 'Auto')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modality',
                'verbose_name_plural': 'Modalities',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('research', 'Research'), ('clinical', 'Clinical'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diagnoses_limit', models.IntegerField(default=10)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('setting_type', models.CharField(choices=[('general', 'General'), ('ai', 'AI Settings'), ('security', 'Security'), ('email', 'Email Settings'), ('payment', 'Payment Settings')], default='general', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('diagnosis', 'Diagnosis'), ('report', 'Report Generated'), ('download', 'Download'), ('payment', 'Payment'), ('profile_update', 'Profile Update'), ('feedback', 'Feedback Submitted'), ('contact', 'Contact Form'), ('view', 'Page View'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('related_record_id', models.IntegerField(blank=True, help_text='ID of related record (e.g., DiagnosisRecord ID)', null=True)),
                ('related_model', models.CharField(blank=True, help_text='Name of related model', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('research', 'Research Collaboration'), ('general', 'General Question'), ('payment', 'Payment Inquiry'), ('other', 'Other')], default='general', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved')], default='new', max_length=50)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('modality', models.CharField(blank=True, choices=[('MRI', 'MRI'), ('CT', 'CT'), ('X-ray', 'X-ray'), ('Micro', 'Micro'), ('auto', 'Auto')], max_length=20, null=True)),
                ('disease_category', models.CharField(blank=True, max_length=50, null=True)),
                ('xai_mode', models.CharField(choices=[('both', 'Grad-CAM + Attention'), ('gradcam', 'Grad-CAM Only'), ('attention', 'Attention Only')], default='both', max_length=20)),
                ('diagnosis', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('probabilities', models.JSONField(blank=True, default=list, null=True)),
                ('is_positive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Review', 'Review'), ('Processing', 'Processing'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('report_generated', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('gradcam_path', models.CharField(blank=True, max_length=255, null=True)),
                ('attention_path', models.CharField(blank=True, max_length=255, null=True)),
                ('report_path', models.CharField(blank=True, max_length=255, null=True)),
                ('inference_time', models.CharField(blank=True, max_length=50, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnosis Record',
                'verbose_name_plural': 'Diagnosis Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Diagnosis History',
                'verbose_name_plural': 'Diagnosis Histories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Diagnosis.diagnosisrecord',),
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
            ],
            options={
                'verbose_name': 'Diagnosis Report',
                'verbose_name_plural': 'Diagnosis Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Diagnosis.diagnosisrecord',),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('diagnosis_complete', 'Diagnosis Complete'), ('report_ready', 'Report Ready'), ('payment_success', 'Payment Success'), ('subscription_expiry', 'Subscription Expiry'), ('welcome', 'Welcome'), ('feedback_request', 'Feedback Request'), ('system_update', 'System Update'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank Transfer'), ('card', 'Credit Card')], default='esewa', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50)),
                ('receipt_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Diagnosis.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_helpful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='Diagnosis.diagnosisrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('researcher', 'Researcher'), ('clinician', 'Clinician'), ('student', 'Student'), ('admin', 'Administrator')], default='researcher', max_length=50)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('subscription_plan', models.CharField(default='free', max_length=50)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('total_diagnoses', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SavedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='Diagnosis.diagnosisrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Analysis',
                'verbose_name_plural': 'Saved Analyses',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'diagnosis_record')},
            },
        ),
    ]
