# Generated by Django 5.2.15 on 2026-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='attention_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='gradcam_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
